### ISSUE TITLE
compile error: The program `elixir.bat` was not found. Is it installed?

### ISSUE THREAD

**Issue by PegasusPlusUS** [mdarse/kmh#1]
error: Program not found

The program `elixir.bat` was not found. Is it installed?

erlang already installed on windows, there's no elixir.bat

**Comment by mdarse** [comment]
Hi,
Can you provide more information on your environnement? (Gleam, Elixir & OS versions at least)

**Comment by PegasusPlusUS** [comment]
erlang        27.1.2           main   2024-10-20 16:59:41
gleam         1.5.1            main   2024-10-11 01:20:32

Windows 11 23H2

Add dependency for kmh, then got 
Build error message:
  Compiling prime
error: Program not found

The program `elixir.bat` was not found. Is it installed?

**Comment by mdarse** [comment]
Oh, I see. This library makes use a the `prime` package which is in Elixir. So yes you need to install Elixir for this to work ATM.

This should have been mentioned in the README, sorry about that.

Actually the `prime` package is only used for validation of parameters, and not strictly required. I will see if current build system allows to make it optional.

Please reopen if the proposed solution doesn’t fix the issue.
